### ISSUE TITLE
Can't install cause need "traceur.js"

### ISSUE THREAD

**Issue by dragonnblack** [Greentube/localize-router#10]
Hello, 

I want to use this [angular2 seed advanced who use ng2-translate](https://github.com/NathanWalker/angular-seed-advanced)

But also I wanted to add your pluggin to add localization on my urls, but when I install, import and launch got the error traceur.js not found, tried to install it but same error.

Any idea?

Regards,

**Comment by koodikindral** [comment]
I've added traceur to my project's config:

```
    additionalPackages.push({
      name: 'traceur',
      path: `${this.APP_BASE}node_modules/traceur/bin`,
      packageMeta: {
        main: 'traceur.js',
        defaultExtension: 'js'
      }
    });
```

**Comment by dragonnblack** [comment]
Thanks you, I had to add rxjs like this too but now it's Ok

Maybe another problem, I import the serviceLocalizeRouterService  as localize, when I use this.localize.changeLanguage() is't ok but on the same view I try the | localize got an error that pipe localize is missing, but i'm doing same than example, any idea? 

Very thanks! :D

**Comment by meeroslav** [comment]
If you get message that pipe localize is missing that means you are using pipe in a module without importing the LocalizeRouterModule. Find all the templates/components where you use '... | localize' and check if their parent module imports LocalizeRouterModule.

**Comment by meeroslav** [comment]
@dragonnblack Please close this issue if solution provided by @koodikindral solved your problem. Thanks!
