### ISSUE TITLE
Can't changelanguage to default with alwaysSetPrefix = false

### ISSUE THREAD

**Issue by kareljuricka** [Greentube/localize-router#102]
Hi,

i tried to changed language to default with localizeRouterService.changeLanguage(defaultLang). But when I do it, I got error message:
```
Uncaught (in promise): TypeError: Cannot read property 'split' of null
TypeError: Cannot read property 'split' of null
    at defaultUrlMatcher (router.js:552)
```

When i set alwaysSetPrefix = true it works but my goal is to have default language without prefix.
 
I also noticed that in my case when I call changeLanguage that is always redirected to homepage with specific new language in url. It can be relative with same issue. I also using lazy loaded modules.

Using Angular 5

**Comment by imsingh** [comment]
@kareljuricka can you replicate the issue with a Plunker?

**Comment by kamil-zielinski** [comment]
I have the same problem.

[Here's a Plunker](https://embed.plnkr.co/Mh5g7NPbB1S83JPNyKk6/). Click 'Change lang to Spanish' and later 'Change lang to English' to see error in the console.

**Comment by xunra** [comment]
I'm pretty sure my PR #97 fixes this, sadly a new version hasn't been released since it was merged.

**Comment by kamil-zielinski** [comment]
Yes, it seems to be related. Can't wait for this to be released. Thank you @xunra.
