### ISSUE TITLE
Translate page title on route's object

### ISSUE THREAD

**Issue by Jassmin586** [Greentube/localize-router#103]
Is there any way to translate page title depending on routes (like 'Register' on screenshot)?

![image](https://user-images.githubusercontent.com/19594765/34748461-e40b3e06-f59c-11e7-85b9-0659a035eee9.png)

**Comment by meeroslav** [comment]
Hi @Jassmin586, which component is using the title from route's data object?

You can use titleService as described in ToddMotto's blog: [https://toddmotto.com/dynamic-page-titles-angular-2-router-events](https://toddmotto.com/dynamic-page-titles-angular-2-router-events)

And then combine it with translate service like this:

```ts
this.router.events
  .filter((event) => event instanceof NavigationEnd)
  .map(() => this.activatedRoute)
  .map((route) => {
    while (route.firstChild) route = route.firstChild;
    return route;
  })
  .filter((route) => route.outlet === 'primary')
  .mergeMap((route) => route.data)
  .subscribe((event) => { 
    const translatedTitle = this.translateService.instant(event['title']);
    this.titleService.setTitle(translatedTitle);
  });
```

**Comment by Jassmin586** [comment]
That's exactly what I was looking for. Thanks a lot! :D
