### ISSUE TITLE
[Documentation] Improvement for router.navigate

### ISSUE THREAD

**Issue by Chuvisco88** [Greentube/localize-router#11]
I ran into an error when trying to navigate in the code `this.router.navigate(['/route']);` directly.
Tried this with the localize-router-example as well but found out a solution for it as below:

`this.localize.translateRoute('route', true).subscribe(
    path => this.router.navigate(['/' + path])
);`

Would be good to note that down somewhere in the readme

**Comment by meeroslav** [comment]
Hi,

I expected [https://github.com/Greentube/localize-router#service](https://github.com/Greentube/localize-router#service) to be clear enough, but I guess it can be improved.

Thanks for bringing that up!

Cleaner way to solve your task would be:
```ts
this.localize.translateRoute('/route', true).subscribe( path => this.router.navigate([path]) );
```
But I guess your solution works just as well.

**Comment by meeroslav** [comment]
@Chuvisco88 Is it more clear now? If not can you suggest how to improve it? Thanks!

**Comment by Chuvisco88** [comment]
Totally clear and thanks for the cleaner way!
