### ISSUE TITLE
Are you ready for Angular 6?

### ISSUE THREAD

**Issue by Dok11** [Greentube/localize-router#110]
In building app I have warning:
```
Warning: Can't resolve all parameters for ManualParserLoader in
../node_modules/localize-router/src/localize-router.parser.d.ts:
([object Object], [object Object], [object Object], ?, ?).
This will become an error in Angular v6.x
```

**Comment by qubiack** [comment]
Don't worry about this. In Angular 4 was a warning that this will become an error in Angular 5.

**Comment by drdreo** [comment]
Just tried to configure localize-router in my Angular 6 Universal app and it errors indexOf at runtime. What is an alternative way for ng6?

**Comment by dyndzio** [comment]
follow - also angular 6 issue.... any alternatives?

**Comment by meeroslav** [comment]
Localize router version 2.x.x now works with Angular 6 and 7

**Comment by PhuQuy** [comment]
Hi @meeroslav , 
I ran into some problems when use universal
Listening on: http://localhost:8080
ERROR { Error: Uncaught (in promise): Error
    at resolvePromise (E:\Demo\hosiana-visitor\dist\server.js:162520:31)
    at resolvePromise (E:\Demo\hosiana-visitor\dist\server.js:162477:17)
    at E:\Demo\hosiana-visitor\dist\server.js:162579:17
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (E:\Demo\hosiana-visitor\dist\server.js:162127:31)
    at Object.onInvokeTask (E:\Demo\hosiana-visitor\dist\server.js:4189:33)
    at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (E:\Demo\hosiana-visitor\dist\server.js:162126:36)
    at Zone.module.exports.Zone.runTask (E:\Demo\hosiana-visitor\dist\server.js:161894:47)
    at drainMicroTaskQueue (E:\Demo\hosiana-visitor\dist\server.js:162301:35)
    at module.exports.ZoneTask.invokeTask (E:\Demo\hosiana-visitor\dist\server.js:162206:21)
    at Server.ZoneTask.invoke (E:\Demo\hosiana-visitor\dist\server.js:162191:48)
  rejection: [Error],
  promise: ZoneAwarePromise { __zone_symbol__state: 0, __zone_symbol__value: [Error] },
  zone:
   Zone {
     _properties: { isAngularZone: true },
     _parent:
      Zone {
        _properties: {},
        _parent: null,
        _name: '<root>',
        _zoneDelegate: [Object] },
     _name: 'angular',
     _zoneDelegate:
      ZoneDelegate {
        _taskCounts: [Object],
        zone: [Circular],
        _parentDelegate: [Object],
        _forkZS: null,
        _forkDlgt: null,
        _forkCurrZone: [Object],
        _interceptZS: null,
        _interceptDlgt: null,
        _interceptCurrZone: [Object],
        _invokeZS: [Object],
        _invokeDlgt: [Object],
        _invokeCurrZone: [Circular],
        _handleErrorZS: [Object],
        _handleErrorDlgt: [Object],
        _handleErrorCurrZone: [Circular],
        _scheduleTaskZS: [Object],
        _scheduleTaskDlgt: [Object],
        _scheduleTaskCurrZone: [Circular],
        _invokeTaskZS: [Object],
        _invokeTaskDlgt: [Object],
        _invokeTaskCurrZone: [Circular],
        _cancelTaskZS: [Object],
        _cancelTaskDlgt: [Object],
        _cancelTaskCurrZone: [Circular],
        _hasTaskZS: [Object],
        _hasTaskDlgt: [Object],
        _hasTaskDlgtOwner: [Circular],
        _hasTaskCurrZone: [Circular] } },
  task:
   ZoneTask {
     _zone:
      Zone {
        _properties: [Object],
        _parent: [Object],
        _name: 'angular',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: ZoneAwarePromise { __zone_symbol__state: 0, __zone_symbol__value: [Error] },
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
ERROR [Error]
ERROR [Error]

Regards,
Quy

**Comment by meeroslav** [comment]
@PhuQuy, I will look into Universal in the upcoming days. Thanks!
