### ISSUE TITLE
v1.0.0-rc.4 release

### ISSUE THREAD

**Issue by yjaaidi** [Greentube/localize-router#114]
Hi @meeroslav!

First of all, thank you for the great job you are doing with this package ! 🎉

It would be awesome if you could release the v1.0.0-rc4 with the latest changes. At Wishtack, for the moment, we are using the master branch as we need the #104 fix 😉and we would love to point on a version instead of a branch or commit tag.

Thank you in advance and keep up the good work!

**Comment by meeroslav** [comment]
Done, sorry for the delay.

**Comment by yjaaidi** [comment]
Thanks!!!
