### ISSUE TITLE
path with :id not being resolve

### ISSUE THREAD

**Issue by gizbo** [Greentube/localize-router#118]
Hi guys,
   I scratching my head here.  My route /en/users/12  is not resolving... Error: Cannot match any routes.   But all other routes that are fix (no params) are working just fine in any language... 
Any idea what I've missed?  
Thanks so much,

**Comment by gilsdav** [comment]
Hello @gizbo ,
Can you provide minimal repo where this can be reproduced ?
Thanks

**Comment by chancezeus** [comment]
I ran into this as well when using prefixed routes, simply put the `translateRoutes` (actual translation happens in `translateText` method inside the parser prefixes ALL url segments, including the ':id' parameter segment.

A similar issue arises from the `translateRoute` method on the service (and by extension the pipe) that (try) to translate string route parameters (anything but string will work fine, but strings (for example slugs) will be prefixed).

I think the `translateText` method should check if the text begins with a ':' and in that case return the text as is (this also fixes #120)

**Comment by meeroslav** [comment]
Closed with 718b8e61be37ac6196f02c4eea41123772b859a3
