### ISSUE TITLE
Word "ROUTES" appearing before route

### ISSUE THREAD

**Issue by Rafael-Miceli** [Greentube/localize-router#119]
Hi there.

We are facing a strange behaviour. After upgrade from version 1.0.0-rc.3 to 1.0.0-rc.4 our routes always appear the word "ROUTES." before the name of the actual route. Can you help me with this behaviour please?

Thx.

**Comment by gilsdav** [comment]
Hello @Rafael-Miceli Take look at my last answer : https://github.com/Greentube/localize-router/issues/111
Add `ROUTES.pathname` to your locale files or remove `ROUTES.` prefix in you _manual parser_ or in `locales.json` file for _http parser_

**Comment by meeroslav** [comment]
Thank you @gilsdav for help.
I will close this issue as resolved.
