### ISSUE TITLE
cli/outlet demos not working

### ISSUE THREAD

**Issue by casvil** [Greentube/localize-router#121]
https://github.com/Greentube/localize-router/tree/master/demo
I have tried cloning both `cli` and `outlet` demos and there is an error on switching language.

Could anyone please provider further information on this?

I need to implement URL localization (without reload) in a SPA and this is the only repository that I have found so far that provides this functionality.

Thanks!

**Comment by casvil** [comment]
The output error is the following:
`Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'de'`

**Comment by Perzonallica** [comment]
It's not working for me neither. Maybe it's connected to this issue here: https://github.com/Greentube/localize-router/issues/115

**Comment by johntrigub** [comment]
Found the reason why the demo does not work?
