### ISSUE TITLE
%Object% after localize pipe

### ISSUE THREAD

**Issue by Dok11** [Greentube/localize-router#134]
This code in template:  
```
<pre>{{ '/news ' | localize }}</pre>
<pre>{{ '/news' | localize }}</pre>
<pre>{{ '/newsa' | localize }}</pre>

<pre>{{ '/about ' | localize }}</pre>
<pre>{{ '/about' | localize }}</pre>
```

working as:
```
<pre>/en/news%20</pre>
<pre>/en/[object Object]</pre>
<pre>/en/newsa</pre>

<pre>/en/about%20</pre>
<pre>/en/about</pre>
```

in package.json i have `"localize-router": "^1.0.0-rc.4",`

**Comment by Dok11** [comment]
What json are we talking about? package.json?

**Comment by gilsdav** [comment]
Your translations (en.json for example)

**Comment by Dok11** [comment]
But I don't use it here, see template in first message.
Only localize pipe

**Comment by gilsdav** [comment]
If you set the prefix of localise router to empty string and you have an en.json with a value like 
{ "news": { "test": "test value" } }, the localize pipe will automaticaly take the value of "news" ([object Object] in this case).
This is how localize-router works.

**Comment by Dok11** [comment]
Your advice about empty string possibly made useful, I will check this version
Thank you! =)

**Comment by meeroslav** [comment]
Thank you @gilsdav for the support!
