### ISSUE TITLE
Working with unit test

### ISSUE THREAD

**Issue by MartynenkoA** [Greentube/localize-router#138]
How can I use this in unit tests, I have error on creation
No provider for LocalizeRouterService!

**Comment by Roelensdam** [comment]
I've the same problem. Can anyone provide an example or a solution ?

**Comment by meeroslav** [comment]
Hi @MartynenkoA and @Roelensdam, if you have a component (or service) using the `LocalizeRouterService` you can mock it out.

This is how I mocked it out in the pipe tests:

```ts
  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [LocalizeRouterPipe],
      providers: [
        { provide: LocalizeRouterService, useClass: MockedLocalizeRouterService }
      ]
    });
    injector = getTestBed();
    localize = injector.get(LocalizeRouterService);

    ref = new FakeChangeDetectorRef();
    localizePipe = new LocalizeRouterPipe(localize, ref);
  });
```

What should be in the `MockedLocalizeRouterService`? That depends what methods or properties are you using:

```ts
class MockedLocalizeRouterService {
  routerEvents: Subject<string> = new Subject<string>();
  parser: DummyLocalizeParser;

  constructor() {
    this.parser = new DummyLocalizeParser();
  }

  translateRoute(route: string | any[]): string | any[] {
    return route + '_TR';
  }
}
```

Hope this helps

**Comment by Ismaestro** [comment]
DummyLocalizeParser: Expected 3 arguments, but got 0.
