### ISSUE TITLE
Should stay on the currnet section if I changed language 

### ISSUE THREAD

**Issue by apolon23** [Greentube/localize-router#139]
Have problems with routing to home page when i change language I need  stay on the currnet section if 
 I changed language 

const routes: Routes = [
  { path: '', component: AdminComponent, children: [
    {path: '', loadChildren: './dashboard-page/dashboard.module#DashboardModule'},
    {path: 'users', loadChildren: './users-page/users.module#UsersModule', data: {preload: true}},
    {path: 'active-jobs', loadChildren: './active-jobs/active-jobs.module#ActiveJobsModule', data: {preload: true}},
]},
  { path: '**', component: NotFoundPageComponent }
];

I see previous solutions with (" ") but it but it does not suit me, i must keep my routes like now.
Maybe you have a any ideas or solution?

**Comment by apolon23** [comment]
Have solve problem like this: 
  onChange(language: string) {
    window.location.href = this.router.url.replace(this.localize.parser.currentLang, language);
  };

**Comment by gilsdav** [comment]
If you are using Angular 6, it's normaly fixed on version 1.0.2 of this fork : https://www.npmjs.com/package/@gilsdav/ngx-translate-router

**Comment by meeroslav** [comment]
Hi @apolon23, please try the latest version - 1.0.1 or 2.0.0-RC.1.

If it still doesn't work, please provide a plunkr, stackblitz or something similar with the minimal repo.

**Comment by meeroslav** [comment]
Duplicate of #95
