### ISSUE TITLE
[Question] No language slugs for default language

### ISSUE THREAD

**Issue by keithazzopardi** [Greentube/localize-router#143]
Is it possible to have the default language without any slugs?

"/home"       >> Default (to be used if no language slug has been specified"
"/en/home" >> English
"/it/home"   >> Italian
"/fr/home"   >> French

**Comment by meeroslav** [comment]
Hi @keithazzopardi, you can choose to either have slugs always:

`en/home` >> default
`it/home` >> Italian
...

Or to have default language ONLY without slugs:
`/home` >> Default
`en/home` X this will fail
`it/home` >> Italian

This is configurable via [LocalizeRouterConfig](https://github.com/Greentube/localize-router#localizerouterconfig):

```ts
    LocalizeRouterModule.forRoot(routes, {
      parser: {
        provide: LocalizeParser,
        useFactory: ManualLoaderFactory,
        deps: [TranslateService, Location, LocalizeRouterSettings]
      },
      alwaysSetPrefix: false,
      useCachedLang: false
    })
```

**Comment by keithazzopardi** [comment]
@meeroslav  Thanks for this. I have some difficulty managing to go around my requirement without useCachedLang.

My requirement is the following:

The first time the user goes to the site it will redirect him to the browser's language. Otherwise, it will redirect him last language.

If the user clicks on en site, it will redirect the  user to the default page.

**Comment by meeroslav** [comment]
The reason why you should choose only one prefixing option - default with or without language prefix, is because otherwise localize-router would not know how to transform following:
```
it/buon/giorno -> en/good/morning ?? /good/morning
```
