### ISSUE TITLE
support for universal

### ISSUE THREAD

**Issue by samvloeberghs** [Greentube/localize-router#17]
is there support described for universal somewhere?

digging trough the source code I suspect not, cause it uses a check for navigator for the browserlanguage. When going for support for universal in node this language could be extracted from the requested_language.

GRtz

**Comment by samvloeberghs** [comment]
More details:

You will need to put a way to define where to load the assets/locales.json.
As an example I would point to your dependecy: ng2-translate. Related issues & gists:
https://github.com/ocombe/ng2-translate/issues/353
https://github.com/angular/universal-starter/issues/263
https://gist.github.com/ocombe/593d21598d988bf6a8609ba5fc00b67e

Will be glad to help out more on this one! Please request my help if needed anywhere

**Comment by meeroslav** [comment]
It would be really helpful if you can set up a universal playground project with localize-router or try to solve this for `localize-router`. Unfortunately I won't have time to play with this until February so any help is appreciated.

**Comment by dneeleman** [comment]
@samvloeberghs Any updates? Would like to integrate this in our Universal App as well.

**Comment by samvloeberghs** [comment]
@dneeleman no sorry.. I came to the conclusion that this plugin is not fitting my needs so I stopped investigating. I'm solving it completely different now.

**Comment by dneeleman** [comment]
@samvloeberghs No problem, what in the plugin doesn't fit your needs if i may ask?

**Comment by samvloeberghs** [comment]
@dneeleman (also check my updated comment above)

Nothing very general, my architecture ( mainly in how I build urls ) and the way I serve the specific app made this plugin not useful. I would use it in other cases I believe ..

**Comment by meeroslav** [comment]
@samvloeberghs and @dneeleman 

I've made some modifications but it's not finalized yet. In order to load localize router config with node use this:

Server loader for `ng2-translate`
```ts
export class TranslateUniversalLoader implements TranslateLoader {
  /**
   * Gets the translations from the server
   * @param lang
   * @returns {any}
   */
  public getTranslation(lang: string): Observable<any> {
    return Observable.create(observer => {
      observer.next(JSON.parse(fs.readFileSync(`assets/locales/${lang}.json`, 'utf8')));
      observer.complete();
    });
  }
}
```
Server loader for `localize-router`
```ts
export class LocalizeUniversalLoader extends LocalizeParser {
  /**
   * Gets config from the server
   * @param routes
   */
  public load(routes: Routes): Promise<any> {
    return new Promise((resolve: any) => {
      let data: any = JSON.parse(fs.readFileSync(`assets/locales.json`, 'utf8'));
      this.locales = data.locales;
      this.prefix = data.prefix;
      this.init(routes).then(resolve);
    });
  }
}
export function localizeLoaderFactory(translate: TranslateService) {
  return new LocalizeUniversalLoader(translate);
}
```

I still need to remove `location` from parser, though, so be patient please.
