### ISSUE TITLE
[Help wanted] Error with 0.6.0

### ISSUE THREAD

**Issue by Chuvisco88** [Greentube/localize-router#21]
Hi @meeroslav 

I upgraded from 0.4.0 to 0.5.0 and then finally to 0.6.0
With the latest version I receive `Error: Template parse errors: The pipe 'translate' could not be found`.

As it only happened, when upgrading this module, I think there might be a bug with the initialization.

```
    LocalizeRouterModule.forRoot(ROUTES),
    RouterModule.forRoot(ROUTES, { useHash: false, preloadingStrategy: PreloadAllModules }),
    TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: (http: Http) => new TranslateStaticLoader(http, '/assets/i18n', '.json'),
      deps: [Http]
    }),
```

Can you provide some assistance?

**Comment by meeroslav** [comment]
Can you try it out by importing TranslateModule before LocalizeRouter?

**Comment by meeroslav** [comment]
Normally this error would mean that your component where the template is referenced is defined in the module that doesn't import TranslateModule.

**Comment by Chuvisco88** [comment]
Tried changing the imports, didn't help so far.
I only import the TranslateModule in the AppModule, that did work up to 0.5.0.
I will try to add it at different places

**Comment by Chuvisco88** [comment]
That was it! I forgot to add the TranslateModule everywhere!
Did add it and it worked.

Fascinatingly it did work with earlier versions without a problem, but is fixed now.
Thanks for your support
