### ISSUE TITLE
Invalid language on URI

### ISSUE THREAD

**Issue by brunorentcars** [Greentube/localize-router#22]
If I set a different language on URI, there isn't on configuration file(locales.json), my application crashes.

There routers for 404:
{path: '404', component: NotFoundComponent},
{path: '**', redirectTo: '404'}

But localize-router put this routers inside children language route.
For example:
{path: '', redirectTo: 'en', pathMatch: 'full'}
{path: 'en', children: [
{path: '404', component: NotFoundComponent},
{path: '**', redirectTo: '404'}
]}

**Comment by Masquer** [comment]
As a workaround you can add a root path redirect after the localize-router was initialized.
like this: this.router.config.push({  path: '**', redirectTo: 'en/404' });
('router' is an instance of Router)
