### ISSUE TITLE
Loading of rxjs.js failed with angular-seed project.

### ISSUE THREAD

**Issue by heyligengregory** [Greentube/localize-router#23]
Hi all,

I try to use localize-router with mgechev/angular-seed. Everything works with ng2-translate but when I try to use localize-router, I have this error : 

`(SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/rxjs.js`
`Error loading http://localhost:5555/node_modules/rxjs.js as "rxjs" from http://localhost:5555/node_modules/localize-router/bundles/localize-router.umd.js`

I tried the same configuration in an angular-cli project and it works perfectly.

Did you try to use ng2-translate && localize-router in an angular-seed project ? Did you already have that kind of errors ?

Thanks for your replies.

**Comment by ruffiem** [comment]
When using localize-router with angular-seed, localize-router tries to resolve dependencies - even the ones that are already loaded - but fails  [(issue)](https://github.com/mgechev/angular-seed/issues/1800#issuecomment-278302289).

**Comment by heyligengregory** [comment]
Hum I saw a response in angular-seed. About adding this in seed.config.ts : 

`packages: {
		'rxjs': {
        main: 'Rx.js',
        defaultExtension: 'js'
      }
    }`

After adding this, the error changed for : 

`(SystemJS) Module not already loaded loading "@angular/core" as http://localhost:5555/node_modules/@angular/core/bundles/core.umd.`


Does this peerDependencies could have an impact on the main error of this issue ? 

`"peerDependencies": {
    "@angular/core": "^2.0.0",
    "@angular/common": "^2.0.0",
    "@angular/http": "^2.0.0",
    "@angular/router": "^3.0.0",
    "rxjs": "^5.0.0",
    "ng2-translate": "^5.0.0"
  }`

It looks like the dependencies which are causing this issue, no ?

**Comment by ruffiem** [comment]
@heyligengregory yes, there's clearly a problem when the module tries to resolve the dependencies. It should not use its own but the ones that are loaded by SystemJS. Did you try to create a production build with the seed ? Production builds do not use SystemJS.

**Comment by fcollombon** [comment]
Are you sure the bug is solved? I have an other error after your update:

```
(SystemJS) XHR error (404 Not Found) loading http://localhost:5555/node_modules/traceur.js
```

**Comment by meeroslav** [comment]
Hi @fcollombon,

the original problem was in Observable and Subject being imported from `rxjs` instead of `rxjs/Observable` and `rxjs/Subject` as well as using generic node exports with webpack bundling. This resolved the original issue. You can see the working application here: [https://github.com/meeroslav/angular-seed-systemjs](https://github.com/meeroslav/angular-seed-systemjs).

Your issue looks like a setup problem. You can open new issue with link to your repo where this can be reproduced and I can try to help.
