### ISSUE TITLE
Issue when using breadcrumb component

### ISSUE THREAD

**Issue by enghelewa** [Greentube/localize-router#24]
![x](https://cloud.githubusercontent.com/assets/939234/22735396/3954b2f0-ee02-11e6-9997-25f8790e331d.png)
Hi,
I am working on multi-culture angular web app and to get culture in URL I am using

> [https://github.com/gmostert/ng2-breadcrumb](https://github.com/gmostert/ng2-breadcrumb)

But found that the current selected culture appear in the breadcrumb component like this:
`Home / En / Campaigns`

Is there any way to remove the culture from the breadcrumb ?

thanks

**Comment by Chuvisco88** [comment]
As far as I could see, ng2-breadcrumb is building on top of the routes which are extended with localize-router.
In my opinion it would make sense for ng2-breadcrumb to check for languages before building upon them.

**Comment by enghelewa** [comment]
Thanks for responding @Chuvisco88 
I solved the problem by just hiding the breadcrumb item related to the culture using css `:nth-child` but a proper solution is to use this function provided by ng2-breadcrumb service
`this.breadcrumbService.hideRouteRegex('^/([A-Za-z]{2})$');`
