### ISSUE TITLE
JSON file with translation is loaded twice

### ISSUE THREAD

**Issue by mrzepinski** [Greentube/localize-router#26]
With `localize-router` I see in my Network tab (Chrome) that the JSON file with current language translations is loaded twice.

"@angular/cli": "1.0.0-beta.31"
"@angular/compiler-cli": ">=4.0.0-beta <5.0.0"
"@angular/common": ">=4.0.0-beta <5.0.0"
"@angular/compiler": ">=4.0.0-beta <5.0.0"
"@angular/core": ">=4.0.0-beta <5.0.0"
"@angular/http": ">=4.0.0-beta <5.0.0"
"@angular/platform-browser": ">=4.0.0-beta <5.0.0"
"@angular/platform-browser-dynamic": ">=4.0.0-beta <5.0.0"
"@angular/router": ">=4.0.0-beta <5.0.0"
"ng2-translate": "5.0.0"
"localize-router": "0.6.2"

**Comment by meeroslav** [comment]
I will look into it, thanks

**Comment by meeroslav** [comment]
@mrzepinski This was a know issue in `ng2-translate` now known as `ngx-translate`. You can find more details here: [https://github.com/ngx-translate/core/issues/397#issuecomment-275368243](https://github.com/ngx-translate/core/issues/397#issuecomment-275368243). It will be resolved once I upgrade to latest version.
