### ISSUE TITLE
Add support for "relativeTo" to "translateRoute" method.

### ISSUE THREAD

**Issue by CamusAran** [Greentube/localize-router#29]
Currently there doesn't seem to be a way navigate to a translated relative path (that I've found).

https://angular.io/docs/ts/latest/api/router/index/NavigationExtras-interface.html#!#relativeTo-anchor

**Comment by meeroslav** [comment]
@CamusAran  Did you try this:

```ts
this.localize.translateRoute('../list').subscribe((path: string) {
  this.router.navigate([path], { relativeTo: this.route });
}
```

**Comment by CamusAran** [comment]
Ok turns out that the issue wasn't what I thought it was, and also I don't actually need to translate the route:
`this.router.navigate(['../', 12345], { relativeTo: this.route });`

The issue I was having was that I have a method in my core service that I'm using to translate the routes and I was somehow passing `['../', 12345]` as a string to `translateRoute(path, true)` which resulted in "/en/../,12345".

So a follow-up question (let me know if you want me to create a new issue for this):
How could something like this be translated `this.router.navigate(['../translate-this', 12345], { relativeTo: this.route });`?

**Comment by meeroslav** [comment]
No, need. I'll add this functionality.

**Comment by meeroslav** [comment]
In the meantime, please use this:
```ts
let translateBatch: Array<Observable<any>> = []; 

yourPath.forEach((segment: any, index: number) => { 
  if (typeof segment === 'string') { 
    translateBatch.push(this.localizeRouterService.translateRoute(segment, index === 0 && segment.indexOf('/') === 0)); 
  } else { 
    translateBatch.push(Observable.of(segment)); 
  } 
}); 
Observable.forkJoin(translateBatch).subscribe((path: any[]) => {
  this.router.navigate(path, { relativeTo: this.route });
});
```
