### ISSUE TITLE
Routes not rewrited if LocalizeRouterService wasn't inject somewhere

### ISSUE THREAD

**Issue by thebarada** [Greentube/localize-router#31]

**Comment by Chuvisco88** [comment]
Not sure what you want to say, but did you initialise the LocalizeRouterModule correctly?
Can you provide some example what you did so far?

**Comment by thebarada** [comment]
I've initialize module like this
in main module:
```
LocalizeRouterModule.forRoot([], {
  provide: LocalizeParser,
  useFactory: (LocalizeParserFactory),
  deps: [TranslateService, Location]
})
```

and in app module
```
LocalizeRouterModule.forChild(routes)
```

But I've errors like `Error: Cannot match any routes. URL Segment: ...` 
until I've inject LocalizeRouterService in any module

now routes works correct, but I think it is a bug

**Comment by thebarada** [comment]
@meeroslav did you publish 0.6.3 version correct? because I have old module file and service as well

**Comment by meeroslav** [comment]
@thebarada I seems that package was not published correctly. Please use version 0.6.4. Thanks for the information.

**Comment by thebarada** [comment]
@meeroslav thnx a lot! I appreciate your help)
