### ISSUE TITLE
Error npm install

### ISSUE THREAD

**Issue by BrunoSalgado** [Greentube/localize-router#33]
When I trying to run npm install, I get the following code:
ERROR in Error encountered resolving symbol values statically. Could not resolve @ngx-translate/core relative to /home/www/mobile/node_modules/localize-router/src/localize-router.module.d.ts., resolving symbol LocalizeRouterModule in /home/www/mobile/node_modules/localize-router/src/localize-router.module.d.ts, resolving symbol LocalizeRouterModule in /home/www/mobile/node_modules/localize-router/src/localize-router.module.d.ts

I'm using:
angular-cli@1.0.0-beta.28.3
Node version 7.4.0
Npm version 4.0.5

**Comment by BrunoSalgado** [comment]
I'm using localize-router@0.6.0 with ng2-translate

**Comment by meeroslav** [comment]
@BrunoSalgado  Are you sure? `ngx-translate` has only been introduced in version 0.6.4. And it requires `ngx-translate` instead of `ng2-translate`. Can you post your package.json?

**Comment by BrunoSalgado** [comment]
`{
  "name": "mobile",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\" --project src/tsconfig.json --type-check && tslint \"e2e/**/*.ts\" --project e2e/tsconfig.json --type-check",
    "test": "ng test",
    "pree2e": "webdriver-manager update --standalone false --gecko false",
    "e2e": "protractor"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/forms": "^2.3.1",
    "@angular/http": "^2.3.1",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "angular2-materialize": "^6.6.0",
    "bower": "^1.8.0",
    "core-js": "^2.4.1",
    "gulp": "^3.9.1",
    "gulp-clean": "^0.3.2",
    "gulp-concat": "^2.6.1",
    "gulp-uglify": "^2.0.1",
    "gulp-util": "^3.0.8",
    "localize-router": "^0.6.0",
    "materialize-css": "^0.98.0",
    "moment": "^2.17.1",
    "ng2-owl-carousel": "^0.1.9",
    "ng2-translate": "^5.0.0",
    "rxjs": "^5.0.1",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^2.3.1",
    "@types/jasmine": "2.5.38",
    "@types/node": "^6.0.42",
    "angular-cli": "1.0.0-beta.28.3",
    "codelyzer": "~2.0.0-beta.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "~4.0.13",
    "ts-node": "1.2.1",
    "tslint": "^4.3.0",
    "typescript": "~2.0.3"
  }
}
`

**Comment by meeroslav** [comment]
Exactly, remove sign `^` in front of version number.
And you'd have to re-run `npm install` and `npm cache clean`.

**Comment by meeroslav** [comment]
Please close the issue if this solves it. Thanks

**Comment by BrunoSalgado** [comment]
This solved. Thank you!
