### ISSUE TITLE
AOT - Calling function 'prepareRoutes', function calls are not supported.

### ISSUE THREAD

**Issue by mrzepinski** [Greentube/localize-router#36]
`ERROR in Error encountered resolving symbol values statically. Calling function 'prepareRoutes', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function`

angular-cli: 1.0.0-rc.2

**Comment by meeroslav** [comment]
@mrzepinski,

Yes, this is the reason why new version with lazy loading is still not published. `prepareRoutes` can be solved with minor change in architecture, but pre-translating the lazy child routes would still not work. Hopefully I'll come up with the solution soon.

**Comment by CamusAran** [comment]
Any update on this?

**Comment by meeroslav** [comment]
`prepareRoutes` are fixed in version 0.7.0 but AOT is still in clash with Lazy Loading, so lazy loading is turned off at the moment.
