### ISSUE TITLE
routerLinkActive not set when toggling lang

### ISSUE THREAD

**Issue by gizbo** [Greentube/localize-router#39]
Hi,
   I'm experiencing an issue with routerLinkActive. When I toggle the lang using the following 
  changeLanguage(lang: string) {
    this.localize.changeLanguage(lang);
  }
It does it's thing and changes the locale and the url accordingly but I loose my nav link highlight controlled by the routerLinkActive.  What should I look for? If I just navigate in without changing locale the highlighting work correctly

Thanks so much,
Yves

**Comment by meeroslav** [comment]
@gizbo Can you provide following information?
- Version of localize-router
- Version of angular
- Route where this is happening

If possible, please provide minimal repo (e.g. plunkr) with this issue.

**Comment by plastikaweb** [comment]
Hi, I've experienced same issue as @gizbo , here you are a plunker: http://plnkr.co/YyBzzt
- Angular 4.1
- localize-router@0.7.0

The selected route gives a yellow background on corresponding item of the main section menu via `router-link-active`, but when changing the language via the language selector menu, the class is not attached to corresponding main section item.

**Comment by meeroslav** [comment]
@plastikaweb Thanks for the plnkr. I will look into it.

**Comment by romanlytvyn** [comment]
I'm also interested in a fix for this, any news?
