### ISSUE TITLE
the current version is not compatible with ng2-translate 4.0.0

### ISSUE THREAD

**Issue by ht89** [Greentube/localize-router#4]
Hello, would you please fix the problem? Because if I used ng2-translate 3.0.0, it would contain bugs.  Thank you a lot.

**Comment by meeroslav** [comment]
Will get to it as soon as possible. Thank you for the information.

**Comment by meeroslav** [comment]
Solved by 07978e59dc3923c5dbe81f58cb7d2e2924510cbc

**Comment by ht89** [comment]
Thank you so much +1:

**Comment by meeroslav** [comment]
You're welcome :)
