### ISSUE TITLE
[Help wanted] How to use router.resetConfig() with localize-router?

### ISSUE THREAD

**Issue by CamusAran** [Greentube/localize-router#40]
I'm trying to dynamically choose which module is shown in root path (not a repro but what I'm trying to implement: https://plnkr.co/edit/Euj4kjDOMQxLJkS8U1P2 ) but I'm running into some issues with integrating localize-router.
I'm guessing the problem is because I'm resetting the config after localize-router has initialized and translated the routes.

localize-router 0.6.2, angular 2.4.0

**Comment by meeroslav** [comment]
`LocalizeRouter` works by hijacking and modifying app routes before the application loads.
Your approach unfortunately would not work with `LocalizeRouter`.

I would suggest to mark pointer to root route you want to change and change it without resetting the routes.

```ts
export function initializeRouteConfig(routes:Routes[], router:Router, loc:Location){
  router.config.forEach(route => {
    if (route.data && route.data.root) {
      route.loadChildren = 'app/b#ModuleB';
    }
  });
  return () => Promise.resolve()
}

@NgModule({
  imports: [
    BrowserModule
    RouterModule.forRoot([
      { path: '', loadChildren: 'app/a#ModuleA', data: { root: true } } 
    ]),
  ],
  declarations: [ App ],
  bootstrap: [ App ],
  providers: [{provide: APP_BOOTSTRAP_LISTENER, useFactory:initializeRouteConfig, deps:[ROUTES, Router, Location], multi: true}
 ]
})
```

You can find modified plunkr [here](https://embed.plnkr.co/FxS8VXSPtoq2paQHfK8k/).

Not sure how complex your actual scenario is, though.

**Comment by CamusAran** [comment]
Thanks, I got it working with LocalizeRouter with your example (with some changes in the forEach since the right configs are one level lower when using LocalizeRouter).

If I did have a more complex scenario, eg. dynamic routes coming form a headless CMS, how could that be solved?
