### ISSUE TITLE
Changing language brings you back to the home page

### ISSUE THREAD

**Issue by brada1703** [Greentube/localize-router#47]
When I click on the following buttons, they bring me back to the home page.
```
<a
      (click)="changeLang('en')" 
      [routerLink]="'/en'" 
      [routerLinkActive]="['router-link-active']">English
</a>
<a 
      (click)="changeLang('it')" 
      [routerLink]="'/it'" 
      [routerLinkActive]="['router-link-active']">Italiano
</a>
```

This is not the desired action. I would instead like it to simply change languages and modify the URL to be /it/pronuncia instead of /en/pronunciation. For example.

I have also tried:
```
<a (click)="changeLang('en')"  
  [routerLinkActive]="['router-link-active']">English</a>
<a (click)="changeLang('it')" 
  [routerLinkActive]="['router-link-active']">Italiano</a>
```

Notice how I removed 

`[routerLink]="'/en'"` and `[routerLink]="'/it'"`

Unfortunately, here, it doesn't change the URL. It simply changes the language. 

I have noticed, in the demo site that you posted, that you can change the URL with the following buttons:
```
  <button (click)="changeLanguage('en')">EN</button>
  <button (click)="changeLanguage('de')">DE</button>
```

So, here the URL and language changes, but you stay on the same page. It does not bring you back to the homepage.

However, if you click
```
  <a [routerLink]="'/en'" [routerLinkActive]="['router-link-active']">EN</a>
  <a [routerLink]="'/de'" [routerLinkActive]="['router-link-active']">DE</a>
```
It does bring you back to the homepage.

Any idea where I could be going wrong?

Thanks guys!

**Comment by meeroslav** [comment]
Hi @brada1703 , 

in the first code example you have both `routerLink` and `(click)`. Most likely your route gets translated with `changeLang` but then navigation via `routerLink` kicks in and redirects you to home.
Try to remove all routerLink bits and leave just click:

```ts
<a (click)="changeLang('en')">English</a>
<a (click)="changeLang('it')">Italiano</a>
```

If you need to mark active language button you can use ngx-translate's `TranslateService` or localize-router `LocalizeService`'s parser to get current language and simply use `ngClass` to mark it.

**Comment by brada1703** [comment]
Thanks again @meeroslav You're the best! 👍 

You're absolutely right. The routerLink was the problem. It kept bringing me back to the homepage. Once I removed it, I realized that the problem then was the "changeLang" part. 

In case anyone else is having a problem with this, let me show you what I changed.

I realized that I was importing 
`import { TranslateService } from '@ngx-translate/core';`
instead of 
`import { LocalizeRouterService } from 'localize-router';`

The problem here is that with @ngx-translate/core, they want to see
```
changeLang(lang:string){
this.translate.use(lang);
```
but in localize-router, your syntax is slightly different
```
  changeLanguage(lang: string) {
    this.localize.changeLanguage(lang);
  }
```

So, I had to change the imports to 'localize-router', the constructor to 
```
  constructor(private localize: LocalizeRouterService) {}

  changeLanguage(lang: string) {
    this.localize.changeLanguage(lang);
  }
```
and finally change the on click event to 
`(click)="changeLanguage('it')"`

Now it works like a charm! 👍

**Comment by AttaHo** [comment]
I used `(click)="changeLanguage('en')"` and the strings are translated but the url does not update accordingly.

I am also getting `Uncaught (in promise): TypeError: Cannot read property 'component' of null` when I change to another language.

Did anyone else have this problem? Please help.
