### ISSUE TITLE
AoT Compilation Errors - AppComponent + Client.ts

### ISSUE THREAD

**Issue by brada1703** [Greentube/localize-router#49]
I am trying to build the app for production and in the command line can run the following with no problem:

`ng build --env=prod `
and
`ng build --prod --aot=false`

However, I would like to build the dev folder with AoT Compilation.

When I run the following command in terminal:

`ng build --prod --aot  `

I get the following error:

```
ERROR in Type AppComponent in /src/app/app.component.ts 

	is part of the declarations of 2 modules: 

	AppModule in /src/app/app.browser.module.ts and 

	AppModule in /src/app/app.node.module.ts! 

Please consider moving 

	AppComponent in /src/app/app.component.ts 

	to a higher module that imports 

	AppModule in /src/app/app.browser.module.ts and 

	AppModule in /src/app/app.node.module.ts. 

You can also create a new NgModule that exports and includes 

	AppComponent in /src/app/app.component.ts 

	then import that NgModule in 

	AppModule in /src/app/app.browser.module.ts and 

	AppModule in /src/app/app.node.module.ts.
```

*side note: I modified the spacing to make it easier to read.

```
as well as

ERROR in ./src/client.ts

Module not found: Error: Can't resolve './$$_gendir/app/app.browser.module.ngfactory' in '/src'

 @ ./src/client.ts 5:0-82

 @ multi ./src/client.ts
```

It is true that I have imported the AppComponent into both the app.browser.module.ts and app.node.module.ts files. However, this is the same as I find in the localize-router-example-master.

Any idea where I could be going wrong here? Should I create a shared service? Or is there a better way to do this?

Thanks!

**Comment by meeroslav** [comment]
Hi @brada1703 ,
As far as I know, there was a change in CLI structure that is causing the error.

Check if this helps: [https://github.com/angular/angular-cli/issues/4888](https://github.com/angular/angular-cli/issues/4888)

Or try to update CLI on your project. [https://github.com/angular/angular-cli#updating-angular-cli](https://github.com/angular/angular-cli#updating-angular-cli)

**Comment by brada1703** [comment]
Thanks @meeroslav. I will follow up with these open issues and follow back up here if I find a solution.

I have tried at least two versions of Angular CLI - "@angular/cli": "^1.0.0", and     "@angular/cli": "^1.0.1", with no luck.

**Comment by brada1703** [comment]
Or would it be better to put this in a shared module?

**Comment by brada1703** [comment]
I was able to get it to compile AoT with your latest [commit](https://github.com/Greentube/localize-router/commit/cf422d471f2b15f50c6beb3a22375fa894c5c123). Thanks @meeroslav
