### ISSUE TITLE
Copying & Pasting URLs not working in production mode

### ISSUE THREAD

**Issue by brada1703** [Greentube/localize-router#50]
After compiled and on a live site, when you copy a URL and paste it into another tab, you receive a 404 error.

Reproduce:
- download https://github.com/Greentube/localize-router/tree/cf422d471f2b15f50c6beb3a22375fa894c5c123
- go into CLI folder
- sudo npm install -g @angular/cli
- ng build --prod
- open site, go to another page, copy page, 
ex. : http://www.URL.com/de/users/Donald%20Knuth
- paste into another tab
- get 404 error

![screen shot 2017-05-08 at 9 33 12 am](https://cloud.githubusercontent.com/assets/16405921/25796430/61d665b0-33d1-11e7-883c-2f401c34a115.png)

However, on the local server, I can copy and paste the URLs with no problem. 

Reproduce:
- download https://github.com/Greentube/localize-router/tree/cf422d471f2b15f50c6beb3a22375fa894c5c123
- go into CLI folder
- sudo npm install -g @angular/cli
- ng serve
- open site, go to another page, copy page, 
ex. : http://localhost:4200/en/users/Donald%20Knuth
- paste into another tab
- the page loads as expected

Any idea what could be happening in the build? Is there any way around it?

Thanks!

**Comment by brada1703** [comment]
Any update on this? For example, is there a working demo from a production site? 

The 404 error is also encountered when refreshing the page. 

Is it possible that this could be fixed via hash routing? Since, then the browser isn't looking for a domain of http://localhost:4200/en/users/Donald%20Knuth but instead is looking for the section http://localhost:4200/#/en/users/Donald%20Knuth within the domain http://localhost:4200/

Just an idea... I'm still researching.

**Comment by brada1703** [comment]
Fixed!! Super stoked!

With this fix, I can now refresh the browser without it giving me a 404 error and, more importantly, share the links with it giving the second user a 404 error.

Okay. So, it's kind of ugly... I'm using the Hash Location Strategy in this case.

Steps:

- within App.Browser.Module.ts

`import { HashLocationStrategy, LocationStrategy } from "@angular/common";
`
and 

```
  providers: [
    {provide: LocationStrategy, useClass: HashLocationStrategy}
  ]
```

Here is a look at the full app.browser.module.ts file:

```
import { UniversalModule } from 'angular2-universal';
import { NgModule } from '@angular/core';
import { Http } from '@angular/http';
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { HashLocationStrategy, LocationStrategy } from "@angular/common";

import { AppComponent } from './app.component';
import { Routes, RouterModule } from '@angular/router';
import { HomeModule } from './home/home.module';
import { LocalizeRouterModule } from 'localize-router';

export function createTranslateLoader(http: Http) {
  return new TranslateHttpLoader(http, '/assets/locales/', '.json');
}

const routes: Routes = [
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: 'users', loadChildren: './users/users.module#UsersModule' },
  { path: '**', redirectTo: 'home' }
];

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    UniversalModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: (createTranslateLoader),
        deps: [ Http ]
      }
    }),
    RouterModule.forRoot(routes),
    LocalizeRouterModule.forRoot(routes),
    HomeModule
  ],
  exports: [RouterModule],
  bootstrap: [AppComponent],
  providers: [
    {provide: LocationStrategy, useClass: HashLocationStrategy}
  ]
})
export class AppModule { }

```

**Comment by brada1703** [comment]
Can someone help me figure out a way to remove the hashtag from the links? 

I'll keep searching in the meanwhile.

**Comment by brada1703** [comment]
In your latest commit, I used the following code for the HashLocationStrategy and it works.

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Http, HttpModule } from '@angular/http';
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { HashLocationStrategy, LocationStrategy } from "@angular/common";

import { AppComponent } from './app.component';
import { AppRoutingModule } from './app-routing.module';
import { HomeModule } from './home/home.module';
import {UsersModule} from "./users/users.module";

export function HttpLoaderFactory(http: Http) {
  return new TranslateHttpLoader(http, '/assets/locales/', '.json');
}

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [ Http ]
      }
    }),
    // feature modules
    HomeModule,
    UsersModule,
    AppRoutingModule
  ],
  providers: [
    {provide: LocationStrategy, useClass: HashLocationStrategy}
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

Thanks!

**Comment by christofferfleat** [comment]
@brada1703 Using a hash url isn't a solution.. You should re-open this.
