### ISSUE TITLE
multisite lang support without url lang prefix

### ISSUE THREAD

**Issue by aperalta02** [Greentube/localize-router#54]
I'm working with this package and I'm asking myself if there's any way to get off the URL lang prefix. For example, if the application is executing in different sites: .com, .es, .de, .fr, etc. I'm able to ask to the API the default lang of the site and set up it in the bootstrapped component so application will know the current lang by the response of the API and I wont need the URL prefix. I think mysite.es/es/perfil or mysite.co.uk/en/profile can be redundant as .es is a spanish TLD so...

Is there any way to remove the URL lang prefix?

**Comment by premiumwd** [comment]
@aperalta02  yes, just use ngx-translate

**Comment by meeroslav** [comment]
As @premiumwd said, in your case you have different languages deployed on different domains, so setting up language via simple config property might be a way to go for you.

`localize-router` is targeted mainly to people that have multiple languages on the same domain.

Does this answer your question?

**Comment by aperalta02** [comment]
Yes it does, thank you very much.
