### ISSUE TITLE
"Cannot match any routes" with links inside a lazy module

### ISSUE THREAD

**Issue by headonkeyboard** [Greentube/localize-router#58]
I'm having an issue with a lazy module but steps to reproduce are quite different than [https://github.com/Greentube/localize-router/issues/25](url) .

App routes : 

```
const routes: Routes = [
  {
    path: 'user',
    loadChildren: 'app/auth/auth.module#AuthModule'
  }
];
```
Auth routes :

```
const routes: Routes = [
  {
    path: '',
    component: AuthComponent,
  },
  {
    path : 'login',
    component: LoginComponent,
  },
  {
    path: 'subscription',
    component: SubscriptionComponent
  }
];
```
- When I enter "http://localhost:4200/en/user/subscription" or "http://localhost:4200/en/user/" directly in browser, there is no problem, components are correctly lazy loaded.

- With "http://localhost:4200/fr/utilisateur" it works great

- But with "http://localhost:4200/fr/utilisateur/inscription" I've got this error `Cannot match any routes. URL Segment: 'fr/utilisateur/inscription'`

I have another problem with this configuration when I put my links directly in the "app.component.html" file. 
- This works : `<a [routerLink]="'/user' | localize">{{ 'Login' | translate }}</a>`
- This needs two clicks on link : `<a [routerLink]="'/user/subscription' | localize">{{ 'Subscription' | translate }}</a>` (First click throw this error `Cannot match any routes. URL Segment: 'fr/utilisateur/inscription'` and second click works)

**Comment by meeroslav** [comment]
It's exactly the problem described in #45. I am closing this as a duplicate.
