### ISSUE TITLE
[Question] How to get current route in different locale

### ISSUE THREAD

**Issue by Chuvisco88** [Greentube/localize-router#6]
Title says it already.
Is there a way to link to the same page in a different locale for direct language switching?

**Comment by meeroslav** [comment]
Please check the https://github.com/meeroslav/localize-router-example.
First two buttons for switching language do exactly that.
In markup you can do something link:
```html
<button (click)="changeLanguage('de')">DE</button>
```
And then in your class:
```typescript
constructor(private localize: LocalizeRouterService) {}

changeLanguage(lang: string) {
    this.localize.changeLanguage(lang);
}
```

**Comment by meeroslav** [comment]
@Chuvisco88 Please close this issue if you question has been answered.

**Comment by Chuvisco88** [comment]
Thanks for the info, the changeLanguage works pretty well.
But another problem arises: When having a button (or a link), how can I mark as active?
I thought of using a function isActive(lang: string) which checks against the localize.parser.currentLang but currently it is always marked as active

**Comment by Chuvisco88** [comment]
Yes, it worked!. Thank you very much
