### ISSUE TITLE
Don't prefix two-letter language name for default locale

### ISSUE THREAD

**Issue by hamstercat** [Greentube/localize-router#63]
Hi there! I have a use case for a project where I need to hide the locale prefix from the URL when it's in the default locale. For example, with the locales `['fr', 'en']` for the URL `/home`:

Currently:
fr => /fr/accueil
en => /en/home

What I need:
fr => /accueil
en => /en/home

I'd like to add a config value to allow for such scenarios. Would you be open to a PR for this use case? Also, while browsing the code, I found the following comment in LocalizeRouterConfig

`  // alwaysSetPrefix: boolean; // TODO this will be implemented later
`

Is this what this settings was supposed to accomplish?

**Comment by meeroslav** [comment]
@hamstercat 
Two letter prefix is needed for application to distinguish which language you want to show the page in.

Logic for getting the language is:
- Language from url (the two letter prefix) or
- Language from cache (LocalStorage or Cache) or
- Language from browser or
- First language from the list

Based on this, if you remove the first two (no prefix and no prior history) language will be selected based on user's browser settings which might be misleading.

I will work on solution that combines [#35](https://github.com/Greentube/localize-router/issues/35) and [#34](https://github.com/Greentube/localize-router/issues/34) (`alwaysSetPrefix`).
