### ISSUE TITLE
[Feature] Enable HttpClientModule

### ISSUE THREAD

**Issue by Chuvisco88** [Greentube/localize-router#64]
Angular introduced the HttpClientModule (https://github.com/angular/angular/commit/37797e2). It is recommended to slowly migrate from HttpModule to this new API.

Would it be possible to extend the localize-router so it supports either of the modules?

**Comment by meeroslav** [comment]
Hi @Chuvisco88, 
It is already supported by extending the `LocalizeParser`. The plan is to completely extract `ngx-translate` and `HttpModule` from parser and have them as optional plugins/loaders to `localize-router`.

Stay tuned for these changes.

**Comment by meeroslav** [comment]
This will be closed with next version of `localize-router-http-loader`. At the moment `localize-router` no longer depends on HttpModule
