### ISSUE TITLE
Disable cachedLang

### ISSUE THREAD

**Issue by Chuvisco88** [Greentube/localize-router#65]
I need to disable the cached language and only use the language from url, browser or first in config.

As far as I can see you did the work for that already in `master` but it is not in the latest npm package.

Do you have an estimation, when it will be published?

As always: Thanks for this awesome repository!

**Comment by meeroslav** [comment]
@Chuvisco88 Hopefully new version will be ready by end of month.
There are some breaking changes so I want to push as much as I can into the next version.
Thanks for the support.

**Comment by Chuvisco88** [comment]
Good to know. Just tell me if there is anything I can help you with

**Comment by meeroslav** [comment]
Solved with https://github.com/Greentube/localize-router/commit/79322db626d55cd10345a07d469206cd3faf93f9

**Comment by Chuvisco88** [comment]
Works superbly, thanks!
