### ISSUE TITLE
Localize-Router doesn't update the url on changeLanguage call

### ISSUE THREAD

**Issue by inova-de** [Greentube/localize-router#66]
Hello everyone,
I am trying to setup a multilingual app with ngx-translate and localize-router.
I have initiated LocalizeRouterModule in the app-routing module like the following:

const medicationsRoutes: Routes = [
    { path: 'medications', component: MedicationsPageComponent },
    { path: 'medications/add', component: AddMedicationPageComponent }
]

const risksRoutes: Routes = [
    { path: 'risks', component: RisksPageComponent }
];

const causesRoutes: Routes = [
    { path: 'cause', component: CausePageComponent }
];

const fallsRoutes: Routes = [
    { path: 'falls', component: FallsPageComponent }
];

const risksCausesFallsRoutes: Routes = [...risksRoutes, ...causesRoutes, ...fallsRoutes];

const patientRoutes: Routes = [
    {
      path: 'add',
      canActivate: [ PatientDoesntExistGuard ],
      component: AddPatientPageComponent
    },
    {
      path: ':id',
      canActivate: [ PatientExistsGuard ],
      children: medicationsRoutes
    }
];

const dashboardRoutes: Routes = [
    { path: '', component: DashboardComponent, children: risksCausesFallsRoutes }
]

const routes: Routes = [
  { path: '', redirectTo: '/dashboard', pathMatch: 'full'},
  { path: 'dashboard', canActivate: [ PatientExistsGuard ], children: dashboardRoutes },
  { path: 'patient', children: patientRoutes },
  { path: '**', redirectTo: '/dashboard' }
];

@NgModule({
  imports: [
    RouterModule.forRoot(routes, {useHash: false}),
    LocalizeRouterModule.forRoot(routes),
    RouterModule.forChild(dashboardRoutes),
    LocalizeRouterModule.forChild(dashboardRoutes),
    RouterModule.forChild(risksCausesFallsRoutes),
    LocalizeRouterModule.forChild(risksCausesFallsRoutes),
    RouterModule.forChild(patientRoutes),
    LocalizeRouterModule.forChild(patientRoutes),
    RouterModule.forChild(medicationsRoutes),
    LocalizeRouterModule.forChild(medicationsRoutes)
  ],
  exports: [ RouterModule, LocalizeRouterModule ]
})
export class AppRoutingModule {}

In my dashboard container i inject the LocalizeRouterService and i have it change the language everytime an event is emitted from a link in a child component.

The language is successfully changed but the URL is not updated.

Can anyone tell me what the issue might be?

Thanks in advance.

**Comment by inova-de** [comment]
Nevermind, a guard was interfering with the localize router service.
I am marking the issue as closed.

**Comment by Jay031** [comment]
@inova-de What did you do wrong exactly?
I have the same problem at this moment. Thanks in advance 👍
