### ISSUE TITLE
Universal server side rendering.

### ISSUE THREAD

**Issue by umeshkumawat** [Greentube/localize-router#70]
I having defficulties with localize-router in server side rendering.  Would you please update the universal example code?

**Comment by meeroslav** [comment]
In the meantime, can you clarify what kind of difficulties are you experiencing?

**Comment by umeshkumawat** [comment]
Hey! thanks for contacting.
Would you please follow the code @ https://github.com/umeshkumawat/Localize-router-universal.git
I took your example code and made some changes per the latest angular universal version. I'll appreciate if you could tell me what I am doing wrong.

**Comment by umeshkumawat** [comment]
Hi, Did you get a chance to review?

**Comment by meeroslav** [comment]
Glad you've solved it. 
Hope you don't mind if I 'steal' changes in your repo to update [localize-router-example](https://github.com/meeroslav/localize-router-example). I will credit you of course.

**Comment by umeshkumawat** [comment]
I'd be more than happy. I'll update the code tomorrow and let you know.

Thanks again for that wonderful piece of module.

**Comment by umeshkumawat** [comment]
I have updated the code.
