### ISSUE TITLE
HELP: - Create dynamic route.

### ISSUE THREAD

**Issue by umeshkumawat** [Greentube/localize-router#71]
Hi,

I want to do something like the followings -
**/en/${value_of_choice}/route**

where:
**${value_of_choice}** - some value based on the chosen language.
Any help is appreciated.

**Comment by meeroslav** [comment]
Is this `value_of_choice` fixed value? 
* If yes, then you can provide it directly in the route translations. Just define your route as e.g. 'value_of_choice/route'.
* If not, then define route as `{value}/route` (rather generic unfortunately), and then you can handle it manually in your code based on language.

For more help please provide a minimal repo or plunkr with your scenario

**Comment by umeshkumawat** [comment]
The `value_of_choice` is a dynamic value. 
Unfortunately I have no experience with plunkr, would you please give me some hint how should I handle the dynamic route based on language.

**Comment by umeshkumawat** [comment]
I was able to customize the prefix with my `value_of_choice` in url using the` localize-router` source code. It is working just fine. I modified the code as follows - 

1. _localize-router.parser.ts_ - In `urlPrefix()`, I made it parametrized with one string parameter.

> urlPrefix(lang: string = this.currentLang) {
>      return this.settings.alwaysSetPrefix || this.currentLang !== this.defaultLang ? lang : '';
>   }

2. _localize-router.parser.ts_ - In `translateRoute()`,  I used `urlPrefix()` in the following location-

> translateRoutes(language: string): Observable<any> {
>     return new Observable<any>((observer: Observer<any>) => {
>       this._cachedLang = language;
>       if (this._languageRoute) {
>         this._languageRoute.path = _**this.urlPrefix(language)**_;
>       }

3. _Localize-router.service.ts_ - Used urlPrefix as a function where ever applicable.

4. Extend the `LocalizeParser` class and override the `urlPrefix()` function in appRoutingModule. This way I successfully modified the route as per my requirement.

I would like to request you to please expose a function that would calculate url prefix so that we can customize it, in this case if urlPrefix() is used everywhere, one can take advantage of it.

**Comment by meeroslav** [comment]
Hi, I still don't know exactly that is you use case for which this would be necessary.

`urlPrefix` will remain getter and unchanged as it's critical for few functionalities in localize-router.

In order to add new method which you can use I need to understand the exact problem you are trying to solve.
Can you please provide more detailed example how and why this would be used (with "exact" routes and scenarios)? Thanks

**Comment by umeshkumawat** [comment]
Hi, 
Let me explain you. I have a requirement in a project. The url should include language and currency, if user changes the language, currency will change accordingly. for example - 
```
pattern: /${locale}/${currency}/${route}
result: /de_DE/EUR/home or /en_US/USD/home
```
Thanks,

**Comment by meeroslav** [comment]
There are two possibilities.

1. Always link currency to language (works most of the times)
    Set up your routes like this:

    ```ts
    const routes: Routes = {
      path: 'currency', children: [
         // ... your normal routes go here 
      ]
    }
    ```

    And then in your translation file e.g. de.json have:
    ```json
    {
      "PREFIX.currency": "EUR"
    }
    ```

2. Use currency as route parameter
  Reason: Some countries are multilingual (e.g. Switzerland, Belgium) while some share same language but not the currency (e.g. USA, UK, Austrialia). Simply linking language to currency might not be accurate, based on your list of languages.

    ```ts
    const routes: Routes = {
      path: ':currency',
      canActivate: [CurrencyAuthGuard] 
      children: [
         // ... your normal routes go here 
      ]
    }
    ```

   This pretty much takes every route prefix (not language, but second segment in url) as potential currency. You need to implement your custom AuthGuard `CurrencyAuthGuard` that will compare current language from `localize-router` and based on whatever config decide if the currency parameter makes sense. This also gives you more manoeuvrability to create really precise and extensive currency validation.

**Comment by meeroslav** [comment]
@umeshkumawat Did any of these solve your issue?

**Comment by meeroslav** [comment]
Closed due to inactivity
