### ISSUE TITLE
Can't resolve all parameters warning

### ISSUE THREAD

**Issue by alexanderknapstein** [Greentube/localize-router#73]
For production build, I get the following warnings. Maybe I'll have the time in the next days to dive into that then I'll give you a note. Cheers, Alex:

Can't resolve all parameters for ManualParserLoader in C:/Users/alexander.knapstein/Development/.../node_modules/localize-router/src/localize-router.parser.d.ts: ([object Object], [object Object], [object Object], ?, ?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for ManualParserLoader in C:/Users/alexander.knapstein/Development/.../node_modules/localize-router/src/localize-router.parser.d.ts: ([object Object], [object Object], [object Object], ?, ?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for LocalizeRouterHttpLoader in C:/Users/alexander.knapstein/Development/.../node_modules/localize-router-http-loader/src/http-loader.d.ts: ([object Object], [object Object], [object Object], [object Object], ?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for LocalizeRouterHttpLoader in C:/Users/alexander.knapstein/Development/.../node_modules/localize-router-http-loader/src/http-loader.d.ts: ([object Object], [object Object], [object Object], [object Object], ?).

**Comment by meeroslav** [comment]
I will look into it. What version of Angular is this happening on? Also, are you using CLI or some custom build/seed?

**Comment by alexanderknapstein** [comment]
I'm using 4.3.6 and CLI

**Comment by GoshaFighten** [comment]
I am getting the same issue. You can see [my project](https://github.com/GoshaFighten/dx-ngx-application). Run `npm run build -- --prod`. You will get

```
PS D:\Issues\dx-ngx-application> npm run build -- --prod

> dx-ngx-application@0.0.0 build D:\Issues\dx-ngx-application
> ng build "--prod"

 11% building modules 9/9 modules 0 activeWarning: Can't resolve all parameters for ManualParserLoader in D:/Issues/dx-ngx-application/node_modules/localize-router/src/localize-router.parser.d.ts: ([object Object], [object Object], [object Object], ?, ?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for ManualParserLoader in D:/Issues/dx-ngx-application/node_modules/localize-router/src/localize-router.parser.d.ts: ([object Object], [object Object], [object Object], ?, ?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for AppManualParserLoader in D:/Issues/dx-ngx-application/src/app/app-manual-parser-loader.ts: ([object Object], [object Object], [object Object], [object Object], ?, ?). This will become an error in Angular v6.x
Warning: Can't resolve all parameters for AppManualParserLoader in D:/Issues/dx-ngx-application/src/app/app-manual-parser-loader.ts: ([object Object], [object Object], [object Object], [object Object], ?, ?). This will become an error in Angular v6.x                                                                                                                    Date: 2017-11-20T23:11:11.941ZHash: 8d1ca3632be7796be8a4
Time: 146334ms
chunk {0} main.c261a548e36057f80f09.bundle.js (main) 4.74 MB [initial] [rendered]
chunk {1} polyfills.231da0978310c502f9fd.bundle.js (polyfills) 61 kB [initial] [rendered]
chunk {2} styles.43a95e7665fa6b44dad7.bundle.css (styles) 447 kB [initial] [rendered]
chunk {3} inline.abdaa9f2febb15b3e13f.bundle.js (inline) 1.45 kB [entry] [rendered]
```

Output from `ng --version`:
```
Angular CLI: 1.5.0
Node: 8.1.4
OS: win32 x64
Angular: 5.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.5
typescript: 2.4.2
webpack: 3.8.1
```

**Comment by qubiack** [comment]
I have similar warning when I use Angular Universal: 
 10% building modules 4/4 modules 0 activeWarning: Can't resolve all parameters for ManualParserLoader in /home/xxxx/Projects/angular4-cli-seed/node_modules/localize-router/src/localize-router.parser.d.ts: ([object Object], [object Object], [object Object], ?, ?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for ManualParserLoader in /home/xxxx/Projects/angular4-cli-seed/node_modules/localize-router/src/localize-router.parser.d.ts: ([object Object], [object Object], [object Object], ?, ?). This will become an error in Angular v5.x

**Comment by meeroslav** [comment]
Can you check if this is still happening with the latest version of localize-router: `1.0.0-rc.3`?

**Comment by Florent-Passerelle** [comment]
Same error with version `1.0.0-rc.3` and Angular CLI.
```
> ng build --aot
 14% building modules 35/35 modules 0 active
 Warning: Can't resolve all parameters for ManualParserLoader in /(...)/node_modules/localize-router/src/localize-router.parser.d.ts: ([object Object], [object Object], [object Object], ?, ?). This will become an error in Angular v6.x
 Warning: Can't resolve all parameters for ManualParserLoader in /(...)/node_modules/localize-router/src/localize-router.parser.d.ts: ([object Object], [object Object], [object Object], ?, ?). This will become an error in Angular v6.x
```

```
> ng --version 
(...)
Angular CLI: 1.5.2
Node: 6.11.4
OS: darwin x64
Angular: 5.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.2
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.2
@schematics/angular: 0.1.5
typescript: 2.4.2
webpack: 3.8.1
```

**Comment by meeroslav** [comment]
Referenced issue in https://github.com/angular/angular/commit/61028fb0e83153357821ef7b52797c641145fa7c
