### ISSUE TITLE
Redirect to default language

### ISSUE THREAD

**Issue by deantoni** [Greentube/localize-router#74]
Hello,

I was wondering there's a known workaround to deal with this:

> Note that localize-router does not redirect routes like my/route to translated ones e.g. en/my/route. All routes are prepended by currently selected language so route without language is unknown to Router.

Perhaps, an event I can subscribe to and check if the route was not found because the language was missing? And then add the default language?

**Comment by meeroslav** [comment]
Hi @deantoni, 
With latest version you can use parameter `alwaysSetPrefix` to skip setting prefix for default language. This way your "old" previous routes would still work.

Other than that you can subscribe to router events and react when event of type `NavigationError` happen. I personally would not recommend this exception driven approach.

**Comment by deantoni** [comment]
Thanks for the quick reply @meeroslav .

 alwaysSetPrefix worked great!

**Comment by janvuk** [comment]
I know the issue is closed but I though I would post this for people coming from google looking a qck fix :p

I get errors using _alwaysSetPrefix_ (and also I don't it to work without a prefix). So I added this to my app.component:

```
router.events.subscribe((event) => {
  if (event instanceof RoutesRecognized && ['', '/'].indexOf(event.url) < 0 && event.url !== 
event.urlAfterRedirects) {
    // Check if URL contains language
    const regexp = '^\\/?(' + locales['locales'].join('|') + ')\\/';
    if (event.url.match(regexp) === null) {
      this.router.navigate([this.localize.translateRoute(event.url)]);
    }
  }
});
````

**Comment by Ra0R** [comment]
> I know the issue is closed but I though I would post this for people coming from google looking for a qck fix :p
> 
> I get errors using _alwaysSetPrefix_ (also I don't want it to work without a prefix). So I added this to my app.component:
> 
> ```
> router.events.subscribe((event) => {
>   if (event instanceof RoutesRecognized && ['', '/'].indexOf(event.url) < 0 && event.url !== 
> event.urlAfterRedirects) {
>     // Check if URL contains language
>     const regexp = '^\\/?(' + locales['locales'].join('|') + ')\\/';
>     if (event.url.match(regexp) === null) {
>       this.router.navigate([this.localize.translateRoute(event.url)]);
>     }
>   }
> });
> ```

This will fail to translate urls which have appended parameters:
/home?gcldi=123

I think one solution to this would be, to remove the parameters and append after translation.
