### ISSUE TITLE
Localized pipe not working on routerLink that has outlets

### ISSUE THREAD

**Issue by pfrendo** [Greentube/localize-router#75]
When I set up `LocalizeRouterModule` and I try to attach `| localize` pipe to `[routerLink]="[{outlets: { modal: ['login'] } }]"` it gives an error that it can't match any routes.

I tried the following:

`[routerLink]="[{outlets: { modal: ['login'] } }] | localize"`
`[routerLink]="[{outlets: { modal: ['login' | localize] } }]"`
`[routerLink]="[{outlets: { modal: ['login'] } | localize }]"`
None work.

Using:
  - Angular - 4.3.*
  - localize-router - 0.7.1

**Comment by pfrendo** [comment]
Any update?

**Comment by meeroslav** [comment]
@pfrendo, unfortunately due to complexity of the router not all the functionalities were covered.
I will try to implement this as soon as possible. Sorry for the delay.

**Comment by pfrendo** [comment]
@meeroslav thank you !

**Comment by fysp11** [comment]
Try this:
`[routerLink]="[('/' | localize),{outlets: { modal: ['login'] } }]"`

**Comment by Roelensdam** [comment]
Is it possible to do it programmactically with "router.navigate()" ?
I'm unable to navigate in my outlet defined in the AppRoutingModule.

```
{ path: '', redirectTo: '/products', pathMatch: 'full' },
    { path: 'products', loadChildren: '../products/products.module#ProductsModule' },
    {
        path: 'lightid',
        component: LightIdentificationComponent,
        outlet: 'modal'
    },
    { path: 'error/:code', component: containers.ErrorPageComponent },
    { path: '**', redirectTo: '/products' }
```

I'm trying to have wizard in a pop-up over the actual content. It seems impossible with ngx-translate when working with routes outlets....

Any help will be appreciated :)
