### ISSUE TITLE
URL not translated to non default language?

### ISSUE THREAD

**Issue by lifenautjoe** [Greentube/localize-router#77]
Hello,

I have followed the sample usage configuration with the following routes.

```ts

export const appRoutes: Routes = [
    {
        path: 'about-us',
        component: AboutUsComponent,
    },
    {
        path: '',
        redirectTo: 'about-us',
        pathMatch: 'full'
    },
    {path: '**', component: PageNotFoundComponent}
];
```
on my translation files 

en.json
```ts
{
    "ROUTES": {
        "about-us": "about-us"
    }
}
```
es.json
```ts
{
    "ROUTES": {
        "about-us": "acerca-de"
    }
}
```

and on the localizeRouterHttpLoader json
```ts
{
    "locales": ["en", "es"]
}
```

The routes `/en/about-us` and /es/about-us` work and change the language accordingly but the route `/es/acerca-de` is not found. 

Is this expected behaviour? Is this library supposed to translate paths too or simply add a prefix to whatever path the route declares to toggle a language change? 

In case it might matter, I am in my AppComponent setting the default language to english too.

Cheers,
Joel.

**Comment by meeroslav** [comment]
Hi @lifenautjoe,

Your path `es/acerca-de` should work. If you are setting the default language in AppComponent that would most likely override settings from LocalizeRouter and could cause this behaviour. Try to use LocalizeRouter to set your default language. Check docs for more information on how default language setting works.

If that doesn't help, please create plunkr or provide link to repo so I can check it in your code.

**Comment by lifenautjoe** [comment]
Hi @meeroslav, 

I made the Plunkr 🎉 .

I can reproduce the same issue in there as you will see when trying to go to the spanish version of a page and found another issue:

When the language changes, the page url doesnt get re-evaluated.
If this is not desired functionality, what are we to do when the user selects another language? How can we send them to the page they are currently but in another language? So from `en/about-us` to `es/acerca-de`

[Here's the plunkr with both issues.](https://embed.plnkr.co/sTVQZXB00TXbbVtiFYFZ/)

**Comment by gilsdav** [comment]
Have you try with :
```
"ROUTES.about-us": "acerca-de"
```
?

**Comment by Kataklism** [comment]
For anyone who might have the same issue, here is what worked for me.
Your basically always need to reference paths using the path translation key instead of the path itself (`ROUTES.about-us` instead of `about-us`). 
```
export const appRoutes: Routes = [
    {
        path: 'about-us',
        component: AboutUsComponent,
    },
    {
        path: '',
        redirectTo: 'about-us',
        pathMatch: 'full'
    },
    {path: '**', component: PageNotFoundComponent}
];
```
Becomes:
```
export const appRoutes: Routes = [
    {
        path: 'ROUTES.about-us',
        component: AboutUsComponent,
    },
    {
        path: '',
        redirectTo: 'ROUTES.about-us',
        pathMatch: 'full'
    },
    {path: '**', component: PageNotFoundComponent}
];
```

If you have any kind of link in a component, you'd use 
```
[routerLink]="['ROUTES.about-us' | localize]" 
```

**Comment by meeroslav** [comment]
The route definition (in en.json, es.json etc.) when a prefix (by default) is used should look like this:

```json
{
   "ROUTES.about-us": "about-us"
}
```

Using object in the JSON file would not work as localize router expects string prefix.
