### ISSUE TITLE
.NET Core 2.0 starter and localize router error

### ISSUE THREAD

**Issue by alexbenitez** [Greentube/localize-router#80]
I'm having problems trying to use the localize-router with .NET Core 2.0 (using the "dotnet new angular" starter) at the time of prerendering. When I enable server-side debugging I can see that LocalizeReouterHttpLoader "appears" to successfully read the locales.json file (if I hard code an invalid file.. e.g. locales1.json I see 404 so I'm sure it is locating the file as shown in the trace below). However, when LocalizeParser.init is called from within the factory I'm getting an error "Cannot read property 'length' of undefined". 
Note that if I go to "vendor.js:88971:23" apparently there is an error with the actual json data at run time (this.locales.length is undefined). Just before the stack trace dump there is trace message showing no errors reading from the locales.json file (Request finished in 0.6473ms 200 application/json).

Note that I've experienced some other errors trying to use the fs.readFileSync which I'll try to address later... for now hardcoding an http URL instead so it should work on the client and server...

Any idea? Thx!

dist\vendor.js:
LocalizeParser.prototype.init = function (routes) {

        var selectedLanguage;

        var wildcardRoute;

	this.routes = routes;
	if (!this.locales.length) {

 		return Promise.resolve();
       
	}
    

locales.json file:
{
    "locales": ["en", "fr"],
    "prefix": "ROUTES"
}

info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:5000/assets/locales.json  0
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/assets/locales.json'. Physical path: 'C:\TFS1\Spikes\localize2\wwwroot\assets\locales.json'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.6473ms 200 application/json
fail: Microsoft.AspNetCore.NodeServices[0]
      ERROR TypeError: Cannot read property 'length' of undefined
          at LocalizeRouterHttpLoader.LocalizeParser.init (C:\TFS1\Spikes\localize2\ClientApp\dist\vendor.js:88359:26)
          at SafeSubscriber._next (C:\TFS1\Spikes\localize2\ClientApp\dist\vendor.js:88971:23)
          at SafeSubscriber.module.exports.SafeSubscriber.__tryOrUnsub (C:\TFS1\Spikes\localize2\ClientApp\dist\vendor.js:574:16)
          at SafeSubscriber.module.exports.SafeSubscriber.next (C:\TFS1\Spikes\localize2\ClientApp\dist\vendor.js:521:22)
          at Subscriber.module.exports.Subscriber._next (C:\TFS1\Spikes\localize2\ClientApp\dist\vendor.js:461:26)
          at Subscriber.module.exports.Subscriber.next (C:\TFS1\Spikes\localize2\ClientApp\dist\vendor.js:425:18)
          at ZoneTask.onComplete [as callback] (C:\TFS1\Spikes\localize2\ClientApp\dist\main-server.js:5420:30)
          at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (C:\TFS1\Spikes\localize2\ClientApp\dist\vendor.js:90874:31)
          at Object.onInvokeTask (C:\TFS1\Spikes\localize2\ClientApp\dist\vendor.js:14778:33)
          at ZoneDelegate.module.exports.ZoneDelegate.invokeTask (C:\TFS1\Spikes\localize2\ClientApp\dist\vendor.js:90873:36)

In the app.module.share.ts I have the following code:

export const routes = [
    { path: '', redirectTo: 'home', pathMatch: 'full' },
    { path: 'home', component: HomeComponent },
    { path: 'counter', component: CounterComponent },
    { path: 'fetch-data', component: FetchDataComponent },
    { path: '**', redirectTo: 'home' }
];

export function HttpLoaderFactory(http) {
    return new TranslateHttpLoader(http);
}

export function HttpRouterLoaderFactory(translate: TranslateService, location: Location, settings: LocalizeRouterSettings, http) {
    //having problems with relative paths... hardcoding URL for now...
    return new LocalizeRouterHttpLoader(translate, location, settings, http, 'http://localhost:5000/assets/locales.json')
}

:
:
:

imports: [
        CommonModule,
        FormsModule,
        HttpClientModule,
        TranslateModule.forRoot({
            loader: {   
                provide: TranslateLoader,
                useFactory: HttpLoaderFactory,
                deps: [Http]
            }
        }),
        LocalizeRouterModule.forRoot(routes, {
            parser: {
                provide: LocalizeParser,
                useFactory: HttpRouterLoaderFactory,
                deps: [TranslateService, Location, LocalizeRouterSettings, Http]
            }
        }),
       
        RouterModule.forRoot(routes)
    ],

**Comment by meeroslav** [comment]
Can you please provide a simple repo that reproduces the error? Thanks

**Comment by alexbenitez** [comment]
Hi Meeroslav,

Sorry for the delay... Unfortunately I'm not able to follow up in the next couples of weeks (I'm travelling). Unfortunately I don't have a simple repo handy. I was modifying a bigger project but we decided to postpone the feature. 

I would like to give it a try using the starter from the universal team (https://github.com/MarkPieszak/aspnetcore-angular2-universal ). This starter already uses "@ngx-translate/core" (client and server side). Wonder if you could modify that starter to localize URL's?

**Comment by alexbenitez** [comment]
Unfortunately the project in which I had got this specific error has gone through many different changes and replaced with a totally different starter (got different errors).

Closing this issue and opening a new one along with a reference repo.
