### ISSUE TITLE
error (warning) when compile on prod mode

### ISSUE THREAD

**Issue by Paul75** [Greentube/localize-router#85]
Hello,

I have an error (warning) when compile on prod mode : 

`10% building modules 7/7 modules 0 activeWarning: Can't resolve all parameters for ManualParserLoader in /Users/far-paul/Sites/lucy/crous78-front/node_modules/localize-router/src/localize-router.parser.d.ts: ([object Object], [object Object], [object Object], ?, ?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for ManualParserLoader in /Users/far-paul/Sites/lucy/crous78-front/node_modules/localize-router/src/localize-router.parser.d.ts: ([object Object], [object Object], [object Object], ?, ?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for LocalizeRouterHttpLoader in /Users/far-paul/Sites/lucy/crous78-front/node_modules/localize-router-http-loader/src/http-loader.d.ts: ([object Object], [object Object], [object Object], [object Object], ?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for LocalizeRouterHttpLoader in /Users/far-paul/Sites/lucy/crous78-front/node_modules/localize-router-http-loader/src/http-loader.d.ts: ([object Object], [object Object], [object Object], [object Object], ?). This will become an error in Angular v5.x`

Thanks

**Comment by meeroslav** [comment]
Hi @Paul75, can you provide more information about your setup:
- Version of Angular
- Build & deploy setup (CLI or something else)
- If possible, also small repo

Thanks

**Comment by Paul75** [comment]
Hello;

- Version of Angular : 4.4.6
- Build & deploy setup (CLI or something else): ng build --base-href=/url/


Thanks

**Comment by Florent-Passerelle** [comment]
Hi,

I think it's a duplicate of #73.

Regards

**Comment by meeroslav** [comment]
Close as it's a duplicate
