### ISSUE TITLE
'OpaqueToken' was not found in '@angular/core'

### ISSUE THREAD

**Issue by nutsoftpt** [Greentube/localize-router#86]
After the update to angular 5, we have this warning.

WARNING in ./node_modules/localize-router/src/localize-router.config.js
11:28-39 "export 'OpaqueToken' was not found in '@angular/core'

Thanks

**Comment by zhongjixiuxing** [comment]
please update to npm

**Comment by fysp11** [comment]
@zhongjixiuxing, can you explain what exactly you mean? I understood "Update you localize-router package to latest". But the the latest version (v1.0.0-rc.0) carries the old OpaqueToken, right?

**Comment by zhongjixiuxing** [comment]
yes, i'm use npm install latest package is include old OpaqueToken code... so, my new project can't run in angular5 with localize-router package
