### ISSUE TITLE
Error: The pipe "localize" could not be found

### ISSUE THREAD

**Issue by Empereol** [Greentube/localize-router#88]
I'm trying to use the `localize` pipe to provide the proper routerlink seen below:

```html
<a [routerLink]="['../', 'donations', donation.id] | localize" queryParamsHandling="merge" translate>admin.donations.table.action.detail</a>
```

But doing so results in an error: "Error: Template parse errors: The pipe 'localize' could not be found"

Is there anything in particular you need to do to use the localize pipe?

**Comment by Empereol** [comment]
Solved it. Entirely my own mistake. I wasn't including/initializing the module and routes properly in my lazy loaded components.

**Comment by christofferfleat** [comment]
@Empereol How did you solve it exactly? I can't get it to work for some reason.

**Comment by Empereol** [comment]
I believe my issue was not importing the Localize Router module into the module where the components I was trying to use the pipe was declared. You either need to import the Localize Router module directly or import a module which exports the Localize Router module into the module which declares the components using the pipe.
