### ISSUE TITLE
Integrating localize-router to the aspnetcore-angular universal starter

### ISSUE THREAD

**Issue by alexbenitez** [Greentube/localize-router#89]
I'm unable to integrate the localize router to a project based on the aspnetcore-angular2-universal starter from Mark Pieszak (based on angular 5). The starter already includes the i18n files which are properly used server (pre-rendering) and client side. I tried unsuccessfully to integrate and use the localize-router module with this becoming-popular .net core starter.

I created a repo at [spnetcore-angular2-universal-with-localize-router](https://github.com/alexbenitez/aspnetcore-angular2-universal-with-localize-router). Please refer to the commit [500530b ](https://github.com/alexbenitez/aspnetcore-angular2-universal-with-localize-router/commit/500530b1cd7f5d46c5b1e234f8d9593e8f93d842) for the partial changes made so far (this is the only commit after cloning the original starter). I left the server-side code in comments (app.module.server.ts).

Wonder if someone could clone this repo (or the original starter) and point me to the right direction as far as the localize-router code that goes in the app.module.browser.ts, app.module.server.ts and app.module.ts (and navmenu component) to display a localize menu link? (unfortunately all the demos that I have seen using the router don't involve .net core 2.0 w/universal)

The current error is "OpaqueToken is not a constructor" but in general this one of many different errors depending on different things that I have tried.

Once cloned, to build the project just run:

npm install && npm run build:dev && dotnet restore

Thanks!

**Comment by meeroslav** [comment]
I will look into it as soon as possible. Thanks

**Comment by meeroslav** [comment]
This is solved with the latest versions.
